### ISSUE TITLE
Woosh Account

### ISSUE THREAD

**Issue by Victorgf87** [pedroandrade/pushwoosh#19]
Hello, I was wondering if this gem works with basic account or which one will I have to purchase?

**Comment by vindia** [comment]
As far as I understand this doesn't work with a Basic account, since the Basic account doesn't allow for Remote API access. The Remote API access is needed for this gem.

**Comment by Victorgf87** [comment]
Thank you for the response, my startup is getting money now, so this won't be a problem anymore.
Thanks for the support, I will be using this gem since I like it so much.
